import { type Dictionary, t } from "intlayer";
import { Metadata } from "next";

const metadataContent = {
  key: "layout-metadata",
  content: {
    title: t({
      en: "Porto Space Team | Home",
      pt: "Porto Space Team | Início",
    }),
    description: t({
      en: "Generated by create next app",
      pt: "Generated by create next app"
    }),
  },
} satisfies Dictionary<Metadata>;

export default metadataContent;